main: ru.ya1.minecraft.terrasmp.TerraSMP
name: TerraSMP
version: 1.0
api-version: 1.13
author: xtend
description: "Something very cool"
commands:
  status:
    description: "Display Statistics"
    usage: /status
  rents:
    description: "Display Rents"
    usage: /rents name days
  debug:
    description: "Admin Command, display stats."
    permission: terrasmp.debug
    usage: /debug